name: Node.js CI

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
        with:
          path: backend

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies (backend)
        working-directory: backend
        run: npm install
      - name: Run backend tests
        working-directory: backend
        env:
          MONGO_URI: ${{ secrets.TEST_MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: npm test

  frontend-tests:
    runs-on: ubuntu-latest
    needs: backend-tests

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
        with:
          path: frontend

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies (frontend)
        working-directory: frontend
             run: npm install
      - name: Run frontend tests
        working-directory: frontend
        run: npm test -- --watchAll=false

